---
all:
  children:
    control_plane:
      hosts:
        control-plane-1:
          ansible_host: "{{ vault_control_plane_1_ip }}"
        control-plane-2:
          ansible_host: "{{ vault_control_plane_2_ip }}"
    workers:
      hosts:
        worker-1:
          ansible_host: "{{ vault_worker_1_ip }}"
    k8s_cluster:
      children:
        control_plane:
        workers:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/latitude_ssh_key
    ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
